# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ayres's blog
email: aliceayres@qq.com
description: 纵有疾风起，人生不言弃
twitter_username: aliceayres88
github_username:  aliceayres

# Build settings
markdown: kramdown
